### ISSUE TITLE
Problem compiling for brcm2708

### ISSUE THREAD

**Issue by hongkongkiwi** [qianguozheng/nodejs-openwrt#1]
I'm trying to compile for brcm2708 and having an issue with python during the install.

Can you test on your machine and see if it works ? (it's for the raspberry pi target).

I'm having this issue:

```
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

**Comment by qianguozheng** [comment]
@hongkongkiwi  which openwrt base version are you using ?
For the error occurred, I guess it should be the Python not installed. You can try install it and set the env, and run `pip install site` to see it.

Ubuntu: `sudo apt-get install python-dev`

**Comment by hongkongkiwi** [comment]
I figured it out, it seems basically that you can't compile this package on 64bit Ubuntu. After changing to a 32bit VM with latest Ubuntu it works just fine.

What a whacky problem!
